[package]
name = "vnsl"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/vnsl_cli",
    "crates/vnsl_compiler",
    "crates/vnsl_core",
    "crates/vnsl_godot",
    "crates/vnsl_parser",
    "crates/vnsl_runtime",
]

[workspace.dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
anyhow = "1.0.95"
thiserror = "1.0.62"
pretty_assertions = "1.4.0"
rayon = "1.10.0"
serde_json = "1.0.128"
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "serde"] }
mlua = { version = "0.10.1", features = ["lua54", "vendored"] }

vnsl_compiler = { path = "crates/vnsl_compiler" }
vnsl_parser = { path = "crates/vnsl_parser" }
vnsl_runtime = { path = "crates/vnsl_runtime" }
vnsl_core = { path = "crates/vnsl_core" }

[dependencies]
vnsl_compiler.workspace = true
vnsl_runtime.workspace = true
anyhow.workspace = true
