[package]
name = "vnsl"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
    "crates/vnsl_compiler",
    "crates/vnsl_parser"
]

[workspace.dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
anyhow = "1.0.86"
thiserror = "1.0.62"

vnsl_compiler = { path = "crates/vnsl_compiler" }
vnsl_parser = { path = "crates/vnsl_parser" }

[dependencies]
vnsl_compiler.workspace = true