[package]
name = "vnsl_godot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
godot = { version = "0.3.4", features = ["api-4-4"] }

anyhow.workspace = true
serde_json.workspace = true
vnsl_compiler.workspace = true
vnsl_runtime.workspace = true
thiserror.workspace = true
vnsl_core.workspace = true
vnsl_parser.workspace = true
bincode.workspace = true
