[package]
name = "vnsl_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua.workspace = true
regex = "1.11.1"
serde.workspace = true
thiserror.workspace = true
vnsl_core.workspace = true
bincode.workspace = true
anyhow.workspace = true
flate2 = "1.1.2"
rand.workspace = true

[dev-dependencies]
vnsl_compiler.workspace = true
pretty_assertions.workspace = true
