script = { SOI ~ scene ~ main_statement ~ labels ~ EOI }

WHITESPACE  = _{ NEWLINE }
COMMENT     = _{ "#" ~ (!"\n" ~ ANY)* }
spacer      = _{ " "* }
indentation = _{ "\t" | " "{4} }

// Core
identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

// Data Types
char      =  {
    !("\"" | "\\" | NEWLINE) ~ ANY
  | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "t")
  | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
line      = @{ char* }
lines     = _{ line ~ (NEWLINE ~ PEEK_ALL ~ line)* }
string    = ${ "\"" ~ lines ~ "\"" }
number    = ${ (NUMBER | ".")+ }
bool      =  { "true" | "false" }
data_type =  { string | number | bool }

// Expressions
arithmetic_op = _{ add | subtract | multiply | divide }
add           =  { "+" }
subtract      =  { "-" }
multiply      =  { "*" }
divide        =  { "/" }

comp_op = { eq | n_eq | gte | gt | lte | lt }
eq      = { "==" }
n_eq    = { "!=" }
gt      = { ">" }
gte     = { ">=" }
lt      = { "<" }
lte     = { "<=" }

literal = { data_type }
group   = { "(" ~ spacer ~ expr ~ spacer ~ ")" }
atom    = { literal | group }

op_expr     = { atom ~ spacer ~ ((arithmetic_op | comp_op) ~ spacer ~ expr ~ spacer)* }
assign_expr = { identifier ~ spacer ~ "=" ~ spacer ~ expr }
expr        = { op_expr | assign_expr }

// Commands
dialogue      = { string }
action        = { "[" ~ identifier ~ args ~ "]" }
args          = { (spacer ~ action_arg)* }
action_arg    = { (identifier ~ ":" ~ spacer)? ~ data_type }
jump          = { "jump" ~ spacer ~ identifier }
var           = { "var" ~ spacer ~ identifier ~ spacer ~ data_type }
set_character = { "char" ~ spacer ~ identifier }
command       = { dialogue | set_character | action | var | jump }

choice        =  {
    string ~ block
}
choices_block = _{
    ":" ~ PEEK_ALL ~ PUSH(indentation) ~ choice ~ (PEEK_ALL ~ choice)* ~ DROP
}
choices       =  {
    "choice" ~ choices_block
}

// Flow
stmt        =  { command | choices | expr }
block_stmt  = _{ !(var) ~ stmt }
block       =  {
    ":" ~ PEEK_ALL ~ PUSH(indentation) ~ block_stmt ~ (PEEK_ALL ~ block_stmt)* ~ DROP
}
label_scope = {
    "label" ~ spacer ~ identifier ~ block
}
scene       =  { "scene" ~ spacer ~ identifier }

main_statement = { stmt* }
labels         = _{ label_scope* }
