WHITESPACE = _{ NEWLINE }
COMMENT = _{ "#" ~ (!"\n" ~ ANY)* }

// Data Types
string = ${ "\"" ~ inner ~ "\"" }
inner = @{ char* }
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

// Commands
dialogue = { string }
action_arg = { string }
action = { "[" ~ identifier ~ (" " ~ action_arg)* ~ "]" }

// Core
identifier = @{ (ASCII_ALPHA | NUMBER)+ }
stmt = { dialogue | action }

indentation = _{ "\t" | "    " }
block = {
	PEEK_ALL ~ PUSH(indentation) ~ stmt ~
    (PEEK_ALL ~ stmt)* ~
    DROP
}

label_scope = {
	"'" ~ identifier ~ ":" ~ block
}

script = { SOI ~ stmt* ~ label_scope* ~ EOI }