script = { SOI ~ scene ~ main_statement ~ labels ~ EOI }

WHITESPACE = _{ NEWLINE }
COMMENT = _{ "#" ~ (!"\n" ~ ANY)* }

spacer = _{ " "+ }

// Data Types
char = {
    !("\"" | "\\" | NEWLINE) ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
line = @{ char* }
lines = _{ line ~ (NEWLINE ~ PEEK_ALL ~ line)* }
string = ${ "\"" ~ lines ~ "\"" }
number = { (NUMBER | ".")+ }
bool = { "true" | "false" }
data_type = { string | number | bool }

// Commands
dialogue = { string }
action_arg = { (identifier ~ ":" ~ spacer)? ~ data_type }
args = { (spacer ~ action_arg)* }
action = { "[" ~ identifier ~ args ~ "]" }

command = { dialogue | action }

// Core
identifier = @{ (ASCII_ALPHA | NUMBER)+ }
stmt = { command }

scene = { "scene" ~ spacer ~ #scene_name = identifier }

indentation = _{ "\t" | " "{4} }
block = {
	PEEK_ALL ~ PUSH(indentation) ~ stmt ~
    (PEEK_ALL ~ stmt)* ~
    DROP
}
label_scope = _{
	"label" ~ spacer ~ identifier ~ ":" ~ block
}

main_statement = { stmt* }
labels = { label_scope* }